export const GET_ALL_NOTIFICATIONS_REQUEST = "GET_ALL_NOTIFICATIONS_REQUEST";
export const GET_ALL_NOTIFICATIONS_SUCCESS = "GET_ALL_NOTIFICATIONS_SUCCESS";
export const GET_ALL_NOTIFICATIONS_FAILED = "GET_ALL_NOTIFICATIONS_FAILED";

export const GET_SINGLE_NOTIFICATIONS_REQUEST =
  "GET_SINGLE_NOTIFICATIONS_REQUEST";
export const GET_SINGLE_NOTIFICATIONS_SUCCESS =
  "GET_SINGLE_NOTIFICATIONS_SUCCESS";
export const GET_SINGLE_NOTIFICATIONS_FAILED =
  "GET_SINGLE_NOTIFICATIONS_FAILED";

export const MARK_SINGLE_AS_READ_REQUEST = "MARK_SINGLE_AS_READ_REQUEST";
export const MARK_SINGLE_AS_READ_SUCCESS = "MARK_SINGLE_AS_READ_SUCCESS";
export const MARK_SINGLE_AS_READ_FAILED = "MARK_SINGLE_AS_READ_FAILED";

export const MARK_ALL_AS_READ_REQUEST = "MARK_ALL_AS_READ_REQUEST";
export const MARK_ALL_AS_READ_SUCCESS = "MARK_ALL_AS_READ_SUCCESS";
export const MARK_ALL_AS_READ_FAILED = "MARK_ALL_AS_READ_FAILED";

export const DELETE_SINGLE_NOTIFICATIONS_REQUEST =
  "DELETE_SINGLE_NOTIFICATIONS_REQUEST";
export const DELETE_SINGLE_NOTIFICATIONS_SUCCESS =
  "DELETE_SINGLE_NOTIFICATIONS_SUCCESS";
export const DELETE_SINGLE_NOTIFICATIONS_FAILED =
  "DELETE_SINGLE_NOTIFICATIONS_FAILED";
