export const ADD_POLICY_REQUEST = "ADD_POLICY_REQUEST";
export const ADD_POLICY_SUCCESS = "ADD_POLICY_SUCCESS";
export const ADD_POLICY_FAILED = "ADD_POLICY_FAILED";

export const GET_ALL_POLICY_REQUEST = "GET_ALL_POLICY_REQUEST";
export const GET_ALL_POLICY_SUCCESS = "GET_ALL_POLICY_SUCCESS";
export const GET_ALL_POLICY_FAILED = "GET_ALL_POLICY_FAILED";

export const UPDATE_POLICY_REQUEST = "UPDATE_POLICY_REQUEST";
export const UPDATE_POLICY_SUCCESS = "UPDATE_POLICY_SUCCESS";
export const UPDATE_POLICY_FAILED = "UPDATE_POLICY_FAILED";

export const DELETE_POLICY_REQUEST = "DELETE_POLICY_REQUEST";
export const DELETE_POLICY_SUCCESS = "DELETE_POLICY_SUCCESS";
export const DELETE_POLICY_FAILED = "DELETE_POLICY_FAILED";
