export const ADD_DEPARTMENT_REQUEST = "ADD_DEPARTMENT_REQUEST";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILED = "ADD_DEPARTMENT_FAILED";

export const GET_ALL_DEPARTMENTS_REQUEST = "GET_ALL_DEPARTMENTS_REQUEST";
export const GET_ALL_DEPARTMENTS_SUCCESS = "GET_ALL_DEPARTMENTS_SUCCESS";
export const GET_ALL_DEPARTMENTS_FAILED = "GET_ALL_DEPARTMENTS_FAILED";

export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILED = "UPDATE_DEPARTMENT_FAILED";

export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILED = "DELETE_DEPARTMENT_FAILED";

export const TRANSFER_EMPLOYEES_REQUEST = "TRANSFER_EMPLOYEES_REQUEST";
export const TRANSFER_EMPLOYEES_SUCCESS = "TRANSFER_EMPLOYEES_SUCCESS";
export const TRANSFER_EMPLOYEES_FAILED = "TRANSFER_EMPLOYEES_FAILED";
