export const SHOW_ALL_EMPLOYEE_LEAVES_REQUEST =
  "SHOW_ALL_EMPLOYEE_LEAVES_REQUEST";
export const SHOW_ALL_EMPLOYEE_LEAVES_SUCCESS =
  "SHOW_ALL_EMPLOYEE_LEAVES_SUCCESS";
export const SHOW_ALL_EMPLOYEE_LEAVES_FAILED =
  "SHOW_ALL_EMPLOYEE_LEAVES_FAILED";

export const ADD_LEAVES_FOR_EMPLOYEE_REQUEST =
  "ADD_LEAVES_FOR_EMPLOYEE_REQUEST";
export const ADD_LEAVES_FOR_EMPLOYEE_SUCCESS =
  "ADD_LEAVES_FOR_EMPLOYEE_SUCCESS";
export const ADD_LEAVES_FOR_EMPLOYEE_FAILED = "ADD_LEAVES_FOR_EMPLOYEE_FAILED";

export const DELETE_LEAVES_FOR_EMPLOYEE_REQUEST =
  "DELETE_LEAVES_FOR_EMPLOYEE_REQUEST";
export const DELETE_LEAVES_FOR_EMPLOYEE_SUCCESS =
  "DELETE_LEAVES_FOR_EMPLOYEE_SUCCESS";
export const DELETE_LEAVES_FOR_EMPLOYEE_FAILED =
  "DELETE_LEAVES_FOR_EMPLOYEE_FAILED";

export const GET_ALL_LEAVES_FOR_EMPLOYEES_REQUEST =
  "GET_ALL_LEAVES_FOR_EMPLOYEES_REQUEST";
export const GET_ALL_LEAVES_FOR_EMPLOYEES_SUCCESS =
  "GET_ALL_LEAVES_FOR_EMPLOYEES_SUCCESS";
export const GET_ALL_LEAVES_FOR_EMPLOYEES_FAILED =
  "GET_ALL_LEAVES_FOR_EMPLOYEES_FAILED";

export const GET_SINGLE_EMPLOYEE_LEAVE_REQUEST =
  "GET_SINGLE_EMPLOYEE_LEAVE_REQUEST";
export const GET_SINGLE_EMPLOYEE_LEAVE_SUCCESS =
  "GET_SINGLE_EMPLOYEE_LEAVE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_LEAVE_FAILED =
  "GET_SINGLE_EMPLOYEE_LEAVE_FAILED";

export const EDIT_LEAVES_FOR_EMPLOYEE_REQUEST =
  "EDIT_LEAVES_FOR_EMPLOYEE_REQUEST";
export const EDIT_LEAVES_FOR_EMPLOYEE_SUCCESS =
  "EDIT_LEAVES_FOR_EMPLOYEE_SUCCESS";
export const EDIT_LEAVES_FOR_EMPLOYEE_FAILED =
  "EDIT_LEAVES_FOR_EMPLOYEE_FAILED";

export const SHOW_SINGLE_EMPLOYEE_LEAVES_REQUEST =
  "SHOW_SINGLE_EMPLOYEE_LEAVES_REQUEST";
export const SHOW_SINGLE_EMPLOYEE_LEAVES_SUCCESS =
  "SHOW_SINGLE_EMPLOYEE_LEAVES_SUCCESS";
export const SHOW_SINGLE_EMPLOYEE_LEAVES_FAILED =
  "SHOW_SINGLE_EMPLOYEE_LEAVES_FAILED";

export const CHANGE_APPROVAL_STATUS_REQUEST = "CHANGE_APPROVAL_STATUS_REQUEST";
export const CHANGE_APPROVAL_STATUS_SUCCESS = "CHANGE_APPROVAL_STATUS_SUCCESS";
export const CHANGE_APPROVAL_STATUS_FAILED = "CHANGE_APPROVAL_STATUS_FAILED";
