export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const GET_ALL_EMPLOYEES_REQUEST = "GET_ALL_EMPLOYEES_REQUEST";
export const GET_ALL_EMPLOYEES_SUCCESS = "GET_ALL_EMPLOYEES_SUCCESS";
export const GET_ALL_EMPLOYEES_FAILED = "GET_ALL_EMPLOYEES_FAILED";

export const GET_SINGLE_EMPLOYEE_REQUEST = "GET_SINGLE_EMPLOYEE_REQUEST";
export const GET_SINGLE_EMPLOYEE_SUCCESS = "GET_SINGLE_EMPLOYEE_SUCCESS";
export const GET_SINGLE_EMPLOYEE_FAILED = "GET_SINGLE_EMPLOYEE_FAILED";

export const EDIT_EMPLOYEE_REQUEST = "EDIT_EMPLOYEE_REQUEST";
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAILED = "EDIT_EMPLOYEE_FAILED";

export const SEARCH_EMPLOYEE_REQUEST = "SEARCH_EMPLOYEE_REQUEST";
export const SEARCH_EMPLOYEE_SUCCESS = "SEARCH_EMPLOYEE_SUCCESS";
export const SEARCH_EMPLOYEE_FAILED = "SEARCH_EMPLOYEE_FAILED";

export const GET_EMPLOYEE_BY_DEPARTMENT_REQUEST = "GET_EMPLOYEE_BY_DEPARTMENT_REQUEST";
export const GET_EMPLOYEE_BY_DEPARTMENT_SUCCESS = "GET_EMPLOYEE_BY_DEPARTMENT_SUCCESS";
export const GET_EMPLOYEE_BY_DEPARTMENT_FAILED = "GET_EMPLOYEE_BY_DEPARTMENT_FAILED";

export const PROMOTE_TO_ADMIN_REQUEST = "PROMOTE_TO_ADMIN_REQUEST"
export const PROMOTE_TO_ADMIN_SUCCESS = "PROMOTE_TO_ADMIN_SUCCESS"
export const PROMOTE_TO_ADMIN_FAILED = "PROMOTE_TO_ADMIN_FAILED"