export const ADD_HOLIDAY_REQUEST = "ADD_HOLIDAY_REQUEST";
export const ADD_HOLIDAY_SUCCESS = "ADD_HOLIDAY_SUCCESS";
export const ADD_HOLIDAY_FAILED = "ADD_HOLIDAY_FAILED";

export const EDIT_HOLIDAY_REQUEST = "EDIT_HOLIDAY_REQUEST";
export const EDIT_HOLIDAY_SUCCESS = "EDIT_HOLIDAY_SUCCESS";
export const EDIT_HOLIDAY_FAILED = "EDIT_HOLIDAY_FAILED";

export const DELETE_HOLIDAY_REQUEST = "DELETE_HOLIDAY_REQUEST";
export const DELETE_HOLIDAY_SUCCESS = "DELETE_HOLIDAY_SUCCESS";
export const DELETE_HOLIDAY_FAILED = "DELETE_HOLIDAY_FAILED";

export const SHOW_HOLIDAYS_REQUEST = "SHOW_HOLIDAYS_REQUEST";
export const SHOW_HOLIDAYS_SUCCESS = "SHOW_HOLIDAYS_SUCCESS";
export const SHOW_HOLIDAYS_FAILED = "SHOW_HOLIDAYS_FAILED";