export const ADD_LEAVE_REQUEST = 'ADD_LEAVE_REQUEST'
export const ADD_LEAVE_SUCCESS = 'ADD_LEAVE_SUCCESS'
export const ADD_LEAVE_FAILED = 'ADD_LEAVE_FAILED'

export const EDIT_LEAVE_REQUEST = 'EDIT_LEAVE_REQUEST'
export const EDIT_LEAVE_SUCCESS = 'EDIT_LEAVE_SUCCESS'
export const EDIT_LEAVE_FAILED = 'EDIT_LEAVE_FAILED'

export const SHOW_LEAVE_REQUEST = 'SHOW_LEAVE_REQUEST'
export const SHOW_LEAVE_SUCCESS = 'SHOW_LEAVE_SUCCESS'
export const SHOW_LEAVE_FAILED = 'SHOW_LEAVE_FAILED'

export const DELETE_LEAVE_REQUEST = 'DELETE_LEAVE_REQUEST'
export const DELETE_LEAVE_SUCCESS = 'DELETE_LEAVE_SUCCESS'
export const DELETE_LEAVE_FAILED = 'DELETE_LEAVE_FAILED'

