export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

export const TOKEN_VALIDATION_REQUEST = 'TOKEN_VALIDATION_REQUEST'
export const TOKEN_VALIDATION_SUCCESS = 'TOKEN_VALIDATION_SUCCESS'
export const TOKEN_VALIDATION_FAILED = 'TOKEN_VALIDATION_FAILED'

export const RESET_PASSWORD_ON_LOGIN_REQUEST = 'RESET_PASSWORD_ON_LOGIN_REQUEST'
export const RESET_PASSWORD_ON_LOGIN_SUCCESS = 'RESET_PASSWORD_ON_LOGIN_SUCCESS'
export const RESET_PASSWORD_ON_LOGIN_FAILED = 'RESET_PASSWORD_ON_LOGIN_FAILED'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED'
